# Generated by Django 3.2.9 on 2022-01-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20211108_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='project',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
