# Generated by Django 3.2.9 on 2022-01-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0004_maker_short_bio'),
        ('projects', '0019_auto_20220112_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='makers.maker'),
        ),
    ]
