# Generated by Django 3.2.9 on 2022-05-06 21:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CistercianDateNftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('wallet_public_key', models.CharField(max_length=200, unique=True)),
                ('date_requested', models.DateField(unique=True)),
                ('sent', models.BooleanField(default=False)),
                ('proof', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
