# Generated by Django 3.2.9 on 2022-05-06 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('maker_email', models.EmailField(blank=True, max_length=254)),
                ('maker_profile_image', models.ImageField(blank=True, upload_to='maker_profile_image/')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=20)),
                ('github_handle', models.CharField(blank=True, max_length=20)),
                ('indiehackers', models.CharField(blank=True, max_length=20)),
                ('personal_website', models.URLField(blank=True)),
                ('interviewed', models.BooleanField(default=False)),
                ('short_bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
